type User {
  id: ID!
  name: String!
}

input AuthInput {
  name: String!
  password: String!
}

type Mutation {
  login(input: AuthInput!): User!
  crateUser(input: AuthInput!): User!
}

type Query {
  me: User
}
