// Code generated by MockGen. DO NOT EDIT.
// Source: ./db/repos/todo/iface.go
//
// Generated by this command:
//
//	mockgen -source=./db/repos/todo/iface.go -destination=./db/repos/todo/mock.go -package=todo
//

// Package todo is a generated GoMock package.
package todo

import (
	context "context"
	reflect "reflect"

	todo "github.com/hiroaki-yamamoto/todo-sample-backend/db/models/todo"
	user "github.com/hiroaki-yamamoto/todo-sample-backend/db/models/user"
	model "github.com/hiroaki-yamamoto/todo-sample-backend/graph/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIList is a mock of IList interface.
type MockIList struct {
	ctrl     *gomock.Controller
	recorder *MockIListMockRecorder
	isgomock struct{}
}

// MockIListMockRecorder is the mock recorder for MockIList.
type MockIListMockRecorder struct {
	mock *MockIList
}

// NewMockIList creates a new mock instance.
func NewMockIList(ctrl *gomock.Controller) *MockIList {
	mock := &MockIList{ctrl: ctrl}
	mock.recorder = &MockIListMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIList) EXPECT() *MockIListMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockIList) List(ctx context.Context, arg1 user.User) ([]todo.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, arg1)
	ret0, _ := ret[0].([]todo.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIListMockRecorder) List(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIList)(nil).List), ctx, arg1)
}

// MockICreate is a mock of ICreate interface.
type MockICreate struct {
	ctrl     *gomock.Controller
	recorder *MockICreateMockRecorder
	isgomock struct{}
}

// MockICreateMockRecorder is the mock recorder for MockICreate.
type MockICreateMockRecorder struct {
	mock *MockICreate
}

// NewMockICreate creates a new mock instance.
func NewMockICreate(ctrl *gomock.Controller) *MockICreate {
	mock := &MockICreate{ctrl: ctrl}
	mock.recorder = &MockICreateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICreate) EXPECT() *MockICreateMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockICreate) Create(ctx context.Context, arg1 user.User, input model.NewTodo) (*todo.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1, input)
	ret0, _ := ret[0].(*todo.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockICreateMockRecorder) Create(ctx, arg1, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockICreate)(nil).Create), ctx, arg1, input)
}

// MockIUpdate is a mock of IUpdate interface.
type MockIUpdate struct {
	ctrl     *gomock.Controller
	recorder *MockIUpdateMockRecorder
	isgomock struct{}
}

// MockIUpdateMockRecorder is the mock recorder for MockIUpdate.
type MockIUpdateMockRecorder struct {
	mock *MockIUpdate
}

// NewMockIUpdate creates a new mock instance.
func NewMockIUpdate(ctrl *gomock.Controller) *MockIUpdate {
	mock := &MockIUpdate{ctrl: ctrl}
	mock.recorder = &MockIUpdateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUpdate) EXPECT() *MockIUpdateMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockIUpdate) Update(ctx context.Context, arg1 user.User, input model.UpdateTodo) (*todo.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1, input)
	ret0, _ := ret[0].(*todo.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIUpdateMockRecorder) Update(ctx, arg1, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIUpdate)(nil).Update), ctx, arg1, input)
}

// MockITodoRepo is a mock of ITodoRepo interface.
type MockITodoRepo struct {
	ctrl     *gomock.Controller
	recorder *MockITodoRepoMockRecorder
	isgomock struct{}
}

// MockITodoRepoMockRecorder is the mock recorder for MockITodoRepo.
type MockITodoRepoMockRecorder struct {
	mock *MockITodoRepo
}

// NewMockITodoRepo creates a new mock instance.
func NewMockITodoRepo(ctrl *gomock.Controller) *MockITodoRepo {
	mock := &MockITodoRepo{ctrl: ctrl}
	mock.recorder = &MockITodoRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITodoRepo) EXPECT() *MockITodoRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockITodoRepo) Create(ctx context.Context, arg1 user.User, input model.NewTodo) (*todo.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1, input)
	ret0, _ := ret[0].(*todo.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockITodoRepoMockRecorder) Create(ctx, arg1, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockITodoRepo)(nil).Create), ctx, arg1, input)
}

// List mocks base method.
func (m *MockITodoRepo) List(ctx context.Context, arg1 user.User) ([]todo.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, arg1)
	ret0, _ := ret[0].([]todo.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockITodoRepoMockRecorder) List(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockITodoRepo)(nil).List), ctx, arg1)
}

// Update mocks base method.
func (m *MockITodoRepo) Update(ctx context.Context, arg1 user.User, input model.UpdateTodo) (*todo.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg1, input)
	ret0, _ := ret[0].(*todo.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockITodoRepoMockRecorder) Update(ctx, arg1, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockITodoRepo)(nil).Update), ctx, arg1, input)
}
