// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package todo

import (
	"github.com/hiroaki-yamamoto/todo-sample-backend/db/models/user"
	"gorm.io/cli/gorm/field"
)

var Todo = struct {
	Id          field.String
	Text        field.String
	WipAt       field.Time
	CompletedAt field.Time
	User        field.Struct[user.User]
}{
	Id:          field.String{}.WithColumn("id"),
	Text:        field.String{}.WithColumn("text"),
	WipAt:       field.Time{}.WithColumn("wip_at"),
	CompletedAt: field.Time{}.WithColumn("completed_at"),
	User:        field.Struct[user.User]{}.WithName("User"),
}
