// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package todo

import (
	"context"
	"strings"

	"github.com/hiroaki-yamamoto/todo-sample-backend/db/models/todo"
	"gorm.io/cli/gorm/typed"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func Repo[T any](db *gorm.DB, opts ...clause.Expression) _RepoInterface[T] {
	return _RepoImpl[T]{
		Interface: typed.G[T](db, opts...),
	}
}

type _RepoInterface[T any] interface {
	typed.Interface[T]
	UpdateText(ctx context.Context, id string, text string) (*todo.Todo, error)
	StartWip(ctx context.Context, id string) (*todo.Todo, error)
	Complete(ctx context.Context, id string) (*todo.Todo, error)
}

type _RepoImpl[T any] struct {
	typed.Interface[T]
}

func (e _RepoImpl[T]) UpdateText(ctx context.Context, id string, text string) (*todo.Todo, error) {
	var sb strings.Builder
	_params := make([]any, 0, 3)

	sb.WriteString("UPDATE ? SET text=? WHERE id=?")
	_params = append(_params, clause.Table{Name: clause.CurrentTable}, text, id)

	var result *todo.Todo
	err := e.Raw(sb.String(), _params...).Scan(ctx, &result)
	return result, err
}

func (e _RepoImpl[T]) StartWip(ctx context.Context, id string) (*todo.Todo, error) {
	var sb strings.Builder
	_params := make([]any, 0, 2)

	sb.WriteString("UPDATE ? SET wip_at=now() WHERE id=?")
	_params = append(_params, clause.Table{Name: clause.CurrentTable}, id)

	var result *todo.Todo
	err := e.Raw(sb.String(), _params...).Scan(ctx, &result)
	return result, err
}

func (e _RepoImpl[T]) Complete(ctx context.Context, id string) (*todo.Todo, error) {
	var sb strings.Builder
	_params := make([]any, 0, 2)

	sb.WriteString("UPDATE ? SET completed_at=now() WHERE id=?")
	_params = append(_params, clause.Table{Name: clause.CurrentTable}, id)

	var result *todo.Todo
	err := e.Raw(sb.String(), _params...).Scan(ctx, &result)
	return result, err
}
