// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type Status struct {
	WipAt       *string `json:"wipAt,omitempty"`
	CompletedAt *string `json:"completedAt,omitempty"`
}

type Todo struct {
	ID     string  `json:"id"`
	Status *Status `json:"status"`
	Text   string  `json:"text"`
	User   *User   `json:"user"`
}

type UpdateTodo struct {
	ID          string  `json:"id"`
	Text        string  `json:"text"`
	WipAt       *string `json:"wipAt,omitempty"`
	CompletedAt *string `json:"completedAt,omitempty"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
