// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTodo struct {
	Text string `json:"text"`
}

type Query struct {
}

type Todo struct {
	ID          string  `json:"id"`
	WipAt       *string `json:"wipAt,omitempty"`
	CompletedAt *string `json:"completedAt,omitempty"`
	Text        string  `json:"text"`
}

type UpdateTodo struct {
	ID          string  `json:"id"`
	Text        string  `json:"text"`
	WipAt       *string `json:"wipAt,omitempty"`
	CompletedAt *string `json:"completedAt,omitempty"`
}
