// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package user

import (
	"gorm.io/cli/gorm/field"
)

var User = struct {
	Id   field.String
	Name field.String
	Hash field.Bytes
}{
	Id:   field.String{}.WithColumn("id"),
	Name: field.String{}.WithColumn("name"),
	Hash: field.Bytes{}.WithColumn("hash"),
}
