name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"
          cache-dependency-path: backend/go.sum

      - name: Install golang-migrate
        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Start Database
        run: make setup

      - name: Run Migrations
        run: make migrate

      - name: Run Tests
        run: make test
